# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: KPMG-agent-pool

steps:

- checkout: self
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Task-2'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Download Azure CLI
      Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile $(Agent.ToolsDirectory)\AzureCLI.msi
      
      # Install Azure CLI silently
      Start-Process msiexec.exe -ArgumentList '/i', "$(Agent.ToolsDirectory)\AzureCLI.msi", '/quiet', '/norestart' -NoNewWindow -Wait
  displayName: 'Install Azure CLI'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Check Azure CLI version
      az --version
  displayName: 'Check Azure CLI version'

  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
      az account set --subscription $(subscriptionId)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Download and install Terraform
      $terraformUrl = "https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_windows_amd64.zip"
      $terraformZipPath = "$(Agent.ToolsDirectory)\terraform.zip"
      $terraformExtractPath = "$(Agent.ToolsDirectory)\terraform"

      Invoke-WebRequest -Uri $terraformUrl -OutFile $terraformZipPath
      Expand-Archive -Path $terraformZipPath -DestinationPath $terraformExtractPath -Force

      # Move Terraform executable to a directory in PATH
      Move-Item -Path "$terraformExtractPath\terraform.exe" -Destination "C:\Windows\System32\terraform.exe" -Force
      terraform --version  # Verify Terraform installation
  displayName: 'Install Terraform'
    

- task: TerraformTaskV4@4
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(build.artifactstagingdirectory)'
    backendServiceArm: 'kpmg-terraform-spn'
    backendAzureRmResourceGroupName: 'sql-rg'
    backendAzureRmStorageAccountName: 'terrastatefilebighand'
    backendAzureRmContainerName: 'kpmgcontainer'
    backendAzureRmKey: 'kpmg-assignment/tfstate'

- task: TerraformTaskV4@4
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(build.artifactstagingdirectory)'

- task: TerraformTaskV4@4
  displayName: Terraform format
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(build.artifactstagingdirectory)'
    customCommand: 'fmt'
    outputTo: console
    environmentServiceNameAzureRM: 'kpmg-terraform-spn'

- task: TerraformTaskV4@4
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(build.artifactstagingdirectory)'
    environmentServiceNameAzureRM: 'kpmg-terraform-spn'
    
- task: TerraformTaskV4@4
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(build.artifactstagingdirectory)'
    environmentServiceNameAzureRM: 'kpmg-terraform-spn'

