# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: KPMG-agent-pool

steps:

- checkout: self
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Task-2'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Download Azure CLI
      Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile $(Agent.ToolsDirectory)\AzureCLI.msi
      
      # Install Azure CLI silently
      Start-Process msiexec.exe -ArgumentList '/i', "$(Agent.ToolsDirectory)\AzureCLI.msi", '/quiet', '/norestart' -NoNewWindow -Wait
  displayName: 'Install Azure CLI'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Check Azure CLI version
      az --version
  displayName: 'Check Azure CLI version'

  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
      az account set --subscription $(subscriptionId)

- task: TerraformInstaller@1
  displayName: Terraform install
  inputs:
    terraformVersion: 'latest'
    

- task: TerraformTaskV4@4
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(build.artifactstagingdirectory)/wordpress-terraform'
    backendServiceArm: 'kpmg-terraform-spn'
    backendAzureRmResourceGroupName: 'sql-rg'
    backendAzureRmStorageAccountName: 'terrastatefilebighand'
    backendAzureRmContainerName: 'kpmgcontainer'
    backendAzureRmKey: 'kpmg-assignment/tfstate'


- task: TerraformTaskV4@4
  displayName: Terraform Import
  inputs:
      provider: 'azurerm'
      command: 'custom'
      customCommand: 'import'
      commandOptions: 'azurerm_resource_group.kpmg-rg /subscriptions/54e8d3d3-ef28-44c4-a74b-2f0d89a1fc16/resourceGroups/wordpress-rg'
      outputTo: 'console'
      environmentServiceNameAzureRM: 'kpmg-terraform-spn'


- task: TerraformTaskV4@4
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(build.artifactstagingdirectory)/wordpress-terraform'

- task: TerraformTaskV4@4
  displayName: Terraform format
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(build.artifactstagingdirectory)/wordpress-terraform'
    customCommand: 'fmt'
    outputTo: console
    environmentServiceNameAzureRM: 'kpmg-terraform-spn'

- task: TerraformTaskV4@4
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(build.artifactstagingdirectory)/wordpress-terraform'
    environmentServiceNameAzureRM: 'kpmg-terraform-spn'
    
- task: TerraformTaskV4@4
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(build.artifactstagingdirectory)/wordpress-terraform'
    environmentServiceNameAzureRM: 'kpmg-terraform-spn'

